-- DROP TABLE IF EXISTS Topics;
DROP TABLE IF EXISTS AllThreads;
DROP TABLE IF EXISTS ARCH;
DROP TABLE IF EXISTS BMT;
DROP TABLE IF EXISTS BLE;
DROP TABLE IF EXISTS BSB;
DROP TABLE IF EXISTS BKB;
DROP TABLE IF EXISTS BCL;
DROP TABLE IF EXISTS BLDS;
DROP TABLE IF EXISTS BWLG;
DROP TABLE IF EXISTS CMP;
DROP TABLE IF EXISTS CLS;
DROP TABLE IF EXISTS CTF;
DROP TABLE IF EXISTS CNG;
DROP TABLE IF EXISTS CHE;
DROP TABLE IF EXISTS CRKT;
DROP TABLE IF EXISTS CT;
DROP TABLE IF EXISTS DNC;
DROP TABLE IF EXISTS DG;
DROP TABLE IF EXISTS DVG;
DROP TABLE IF EXISTS FSH;
DROP TABLE IF EXISTS FB;
DROP TABLE IF EXISTS GLF;
DROP TABLE IF EXISTS GYM;
DROP TABLE IF EXISTS HS;
DROP TABLE IF EXISTS HG;
DROP TABLE IF EXISTS HKG;
DROP TABLE IF EXISTS HOK;
DROP TABLE IF EXISTS HNT;
DROP TABLE IF EXISTS ICSK;
DROP TABLE IF EXISTS JR;
DROP TABLE IF EXISTS KYK;
DROP TABLE IF EXISTS KB;
DROP TABLE IF EXISTS LCRS;
DROP TABLE IF EXISTS MA;
DROP TABLE IF EXISTS PDLB;
DROP TABLE IF EXISTS PB;
DROP TABLE IF EXISTS PKR;
DROP TABLE IF EXISTS PKB;
DROP TABLE IF EXISTS PLT;
DROP TABLE IF EXISTS PP;
DROP TABLE IF EXISTS QDC;
DROP TABLE IF EXISTS RKB;
DROP TABLE IF EXISTS RFT;
DROP TABLE IF EXISTS RC;
DROP TABLE IF EXISTS RS;
DROP TABLE IF EXISTS RGB;
DROP TABLE IF EXISTS RNG;
DROP TABLE IF EXISTS SKTB;
DROP TABLE IF EXISTS SKI;
DROP TABLE IF EXISTS SLKL;
DROP TABLE IF EXISTS SLD;
DROP TABLE IF EXISTS SNKL;
DROP TABLE IF EXISTS SNB;
DROP TABLE IF EXISTS SOCC;
DROP TABLE IF EXISTS SFTB;
DROP TABLE IF EXISTS SQSH;
DROP TABLE IF EXISTS SWM;
DROP TABLE IF EXISTS TEN;
DROP TABLE IF EXISTS TAF;
DROP TABLE IF EXISTS UF;
DROP TABLE IF EXISTS VLB;
DROP TABLE IF EXISTS WLK;
DROP TABLE IF EXISTS WVB;
DROP TABLE IF EXISTS WTL;
DROP TABLE IF EXISTS WFB;
DROP TABLE IF EXISTS WRST;
DROP TABLE IF EXISTS YG;

-- Drop topics table
DROP TABLE IF EXISTS Topics;

-- Drop users
DROP TABLE IF EXISTS users;

-- Drop Role_Perm
DROP TABLE IF EXISTS RolePerm;

-- Drop Permissions
DROP TABLE IF EXISTS Permissions;

-- Drop Roles
Drop TABLE IF EXISTS Roles;